---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_bags_path: "data_bags"
  roles_path: "roles"
  environments_path: "environments"
  require_chef_omnibus: true

platforms:
- name: ubuntu-14.04
  run_list:
  - recipe[apt]
- name: ubuntu-16.04
  run_list:
  - recipe[apt]
- name: centos-6.7
  run_list:
  - recipe[yum]
- name: centos-7.2
  run_list:
  - recipe[yum]

suites:
- name: default
  run_list:
    - recipe[camo]
  attributes:
