name 'faye'
maintainer 'Andrey Sidorov'
maintainer_email 'takandar@gmail.com'
license 'MIT'
description 'Configures faye'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
issues_url 'https://github.com/morr/faye-cookbook/issues'
source_url 'https://github.com/morr/faye-cookbook/'
version '0.1.0'
supports 'debian', '>= 7.0'
supports 'ubuntu', '>= 12.04'
supports 'centos', '>= 6.6'
supports 'redhat', '>= 6.6'
supports 'fedora'
supports 'amazon'
depends 'nodejs'
depends 'git'
